name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Usa la versione che preferisci

    - name: Install dependencies
      run: npm ci

    - name: Mostra il report di coverage (testuale)
      run: npm test -- --coverage
